config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  # devise_for :users do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end

  root 'static_pages#home'

  get 'about', to: 'static_pages#about'
  get 'help', to: 'static_pages#help'
  get 'contact', to: 'static_pages#contact'

  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.superadmin_role?
      can :manage, :all
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :manage, :dashboard         # allow access to dashboard
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 255 }
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :send_admin_mail
  def send_admin_mail
    UserMailer.send_welcome_email(self).deliver_later
  end

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    posts_path
  end

  before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = current_user.posts.all
  end

  def show
    @post = current_user.posts.find params[:id]
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new post_params

    if @post.save
      flash[:success] = 'Your post has successfully added'
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = current_user.posts.find params[:id]
  end

  def update
    @post = current_user.posts.find params[:id]

    if @post.update post_params
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    current_user.posts.find(params[:id]).destroy
    redirect_to posts_url
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:home, :about, :help, :contact]

  def home
  end

  def about
  end

  def help
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    © 2021 <a href="https://github.com/mrabets">Mrabets</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Help", help_path %></li>
<!--      <li><%#= link_to "Contact", contact_path %></li>-->
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "lite blog", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Add", new_post_path %></li>
          <li><%= link_to "Show", posts_path %></li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Account
            </a>
            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
              <li><%= link_to "Profile", '#' %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
              <li><%= link_to('Edit registration', edit_user_registration_path) %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to('Sign in', new_user_session_path) %></li>
          <li><%= link_to('Sign up', new_user_registration_path) %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title><%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>  
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


    <%= stylesheet_link_tag '//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/le-frog/jquery-ui.min.css' %>
    <%# dropdown menu %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>

  </head>

  <body>



    <%= render 'layouts/header' %>
    <div class="container">
      <% if notice %>
        <div class="alert alert-success"><%= notice %></div>
      <% elsif alert %>
        <div class="alert alert-danger"><%= alert %></div>
      <% else %>
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
      <%#= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <div class="form-group">
    <%= render 'shared/error_messages' %>
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
    <br>
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control', rows: 7 %>
    <br>
    <%= f.submit 'Create Post', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
  <div class="page-header">
    <h1>Edit Post</h1>
  </div>
</div>
<div class="container">
  <%= render 'form' %>
  <%= link_to 'Back', posts_path, class: 'label label-primary' %>
</div>

app/views/posts/index.html.erb
<h1>Posts</h1>

<div class="container">
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td> <%= link_to 'Show', post %> </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="page-header">
    <h1>Add Post</h1>
  </div>
</div>
<div class="container">
  <%= render 'form' %>
  <%= link_to 'Back', posts_path, class: 'label label-primary' %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <h1><%= @post.title %></h1>
  <span class="label label-primary"> Last update <%= @post.updated_at.strftime("%b %d, %Y") %></span>
</div>
<div class="container">
  <div class="panel panel-default">
    <div class="panel-body">
      <p>
        <%= @post.content %>
      </p>
    </div>
    <div class="panel-footer">By @mrabets</div>
  </div>
  <%= button_to 'Edit', edit_post_path(@post), method: :get, class: "btn btn-primary btn-sm" %><br>
  <%= button_to 'Delete', post_path(@post), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-primary btn-sm" %>
  <hr><%= link_to 'Back', posts_path, class: 'label label-primary' %>
</div>

app/views/shared/_error_messages.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@post.errors.count, "error") %>.
    </div>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<div class="container">
  <div class="page-header">
    <h1>About</h1>
  </div>
  <p>
    Welcome to Just Blog, your number one source for posts. We're dedicated to giving you a focus on minimalism.
   </p>
</div>

app/views/static_pages/contact.html.erb
<div class="container">
  <div class="page-header">
    <h1>Contact</h1>
  </div>
  <p>

  </p>
</div>

app/views/static_pages/help.html.erb
<div class="container">
  <div class="page-header">
    <h1>Help</h1>
  </div>
  <p>
    To start using the service:<br>
    <br>1. Sign up / sign in your account
    <br>2. Press 'Add' button on navbar menu
    <br>3. Create your post (write title and content)
    <br>4. Check your all posts (press 'Show' button)
    <br>5. Enjoy!
  </p>
</div>

app/views/static_pages/home.html.erb
<title><%= provide(:title, "Home") %></title>

  <div class="center jumbotron">
    <div class="p-3 mb-2 bg-secondary text-white">
      <h1>Welcome to the Just Blog</h1>
      <h2>
        Take notes and write ideas without being distracted by unnecessary things
      </h2>
      <%= link_to "Sign up for free", new_user_registration_path, class: "btn btn-lg btn-success" %>
    </div>
  </div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>